# ===========================
# Dev profile overrides
# ===========================
spring.thymeleaf.cache=false

logging.level.tech.wenisch.proxera=DEBUG
logging.level.org.springframework.web.socket=DEBUG
