{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "proxera.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxera.labels" . | nindent 4 }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
