apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxera.fullname" . }}
  labels:
    {{- include "proxera.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxy.port }}
      targetPort: {{ .Values.service.proxy.targetPort }}
      protocol: TCP
    - name: admin
      port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.targetPort }}
      protocol: TCP
  selector:
    {{- include "proxera.selectorLabels" . | nindent 4 }}
