{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "proxera.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxera.labels" . | nindent 4 }}
{{- end }}
